version: "3"

services:
  # kutt:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   depends_on:
  #     - postgres
  #     - redis
  #     - mailpit
  #   ports:
  #     - "3010:3010"
  #   command:
  #     ["sh", "wait-for-it.sh", "postgres:5432", "--", "npm", "run", "dev"]
  #   env_file:
  #     - .env
  #   environment:
  #     DB_HOST: postgres
  #     DB_NAME: kutt
  #     DB_USER: user
  #     DB_PASSWORD: pass
  #     REDIS_HOST: redis

  #   volumes:
  #     - ./:/usr/src/app
  #     - ./.env:/usr/src/app/.env

  redis:
    image: redis:6.0-alpine
    volumes:
      - redis_data:/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kutt
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
  mailpit_data:
